version: "3"
services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGUSER: ${DB_USER}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          files:
            - ./**/*.py
    environment:
      # Override DATABASE_URL from .env with host and port (db:5432) of DB service
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@postgres:${DB_PORT}/${DB_NAME}"
    ports:
      - "${PORT:-8080}:8000"
    depends_on:
      postgres:
        condition: service_healthy
