version: "3"
services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: agpt_live
      POSTGRES_PASSWORD: bnfaHGGSDF134345
      POSTGRES_DB: codegen
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DATABASE_URL=postgres://agpt_live:bnfaHGGSDF134345@postgres:5432/codegen
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      
 