name: Setup Environment and Dependencies
description: Setup the environment and install dependencies for the project

runs:
    using: composite
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Set up Python dependency cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}-${{ steps.get_date.outputs.date }}

    - name: Install Python dependencies
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install

    - name: Install Dependencies
      shell: bash
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Generate Prisma Client
      shell: bash
      run: poetry run prisma generate

    - name: Set DB URL
      shell: bash
      run: echo "DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@localhost:5432/${{ secrets.DB_NAME }}" >> $GITHUB_ENV

    - name: Run Database Migrations
      shell: bash
      run: |
        poetry run prisma migrate dev --name updates

    - name: Populate Database
      shell: bash
      run: |
        ./run populate-db

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: 5432
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RUN_ENV: local
      PORT: 8080
