name: Python Code Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort ruff

    - name: Run isort
      run: isort .

    - name: Run ruff formatter
      run: ruff format . --check
      