name: Python Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set Environment and Install Dependencies
        uses: ./.github/setup-env

      - name: Test with pytest
        run: poetry run pytest --cov .
